# configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: my-app
data:
  # Application configuration
  APP_NAME: "My Kubernetes App"
  APP_VERSION: "1.0.0"
  NODE_ENV: "production"
  # Database configuration
  DB_HOST: "localhost"
  DB_PORT: "5432"
  # API configuration
  API_URL: "http://api-service:3000"
  # Frontend configuration
  NGINX_PORT: "80"
