# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: web-service
  namespace: my-app
  labels:
    app: web-app
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: web-app
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: my-app
  labels:
    app: api-app
spec:
  type: ClusterIP
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: api
  selector:
    app: api-app
